ci: test patches for older minor versions with correct dependencies

diff --git a/.github/workflows/INTEGRATION_TEST.yml b/.github/workflows/INTEGRATION_TEST.yml
--- a/.github/workflows/INTEGRATION_TEST.yml
+++ b/.github/workflows/INTEGRATION_TEST.yml
@@ -2,12 +2,17 @@
 name: Integration test
 
 on:
+  push:
+    branches:
+      - release/*
   workflow_dispatch:
     inputs:
-      connectors_version:
-        description: 'The version of the connectors to test'
-        required: true
-        default: 'SNAPSHOT'
+      connectors-version:
+        description: 'The version of the connectors to test. If not provided, the version is determined based on the Maven project version. On main branch, the default is SNAPSHOT'
+        required: false
+      helm-branch:
+        description: 'The branch of the Helm chart to test against. If not provided, the branch is determined based on the ref (see helm-git-refs.json)'
+        required: false
 
 defaults:
   run:
@@ -17,13 +22,51 @@ defaults:
 
 jobs:
   helm-deploy:
-    name: Helm chart Integration Tests
-    uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
-    secrets: inherit
-    with:
-      identifier: connectors-int
-      test-enabled: true
-      extra-values: |
-        connectors:
-          image:
-            tag: ${{ github.event.inputs.connectors_version }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install jq
+        run: sudo apt-get install jq
+
+      - name: Determine current Maven project version
+        id: maven-version
+        run: |
+          echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
+
+      - name: Determine version of the Connectors image to use
+        id: connectors-version
+        run: |
+          if [ -z "${{ github.event.inputs.connectors-version }}" ]; then
+            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+              echo "::set-output name=connectors-version::SNAPSHOT"
+            else
+              echo "::set-output name=connectors-version::${{ steps.maven-version.outputs.version }}"
+            fi
+          else
+            echo "::set-output name=connectors-version::${{ github.event.inputs.connectors-version }}"
+          fi
+
+      - name: Determine Helm chart ref to use
+        run: |
+          if [ -z "${{ github.event.inputs.helm-branch }}" ]; then
+            helm_branch=$(jq -r ".[\"${{ github.ref }}\"]" .github/workflows/helm-git-refs.json)
+            if [ -z "$helm_branch" ]; then
+              echo "::error::Could not determine Helm chart branch to use, please provide helm-branch input or adjust the mappings in .github/workflows/helm-git-refs.json"
+              exit 1
+            fi
+            echo "::set-output name=helm-branch::$helm_branch"
+          else
+            echo "::set-output name=helm-branch::${{ github.event.inputs.helm-branch }}"
+          fi
+      - name: Helm chart Integration Tests
+        uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
+        secrets: inherit
+        with:
+          identifier: connectors-int
+          camunda-helm-git-ref: ${{ steps.helm-branch.outputs.helm-branch }}
+          test-enabled: true
+          extra-values: |
+            connectors:
+              image:
+                tag: ${{ steps.connectors-version.outputs.connectors-version }}
