clean up

diff --git a/.github/workflows/RELEASE.yaml b/.github/workflows/RELEASE.yaml
--- a/.github/workflows/RELEASE.yaml
+++ b/.github/workflows/RELEASE.yaml
@@ -23,8 +23,13 @@ jobs:
       - name: Validate release tag and determine previous tag
         id: validate_tag
         run: |
-          echo "type=RC" >> $GITHUB_OUTPUT
-          echo "previousTag=8.8.0-alpha2" >> $GITHUB_OUTPUT
+          OUTPUT="$(.github/workflows/scripts/prev_tag.sh ${{ github.event.release.tag_name }})"
+          if [ $? -ne 0 ]; then
+            echo "Script failed"
+            exit 1
+          fi
+          echo "type=$( echo $OUTPUT | cut -d ' ' -f1 )" >> $GITHUB_OUTPUT
+          echo "previousTag=$( echo $OUTPUT | cut -d ' ' -f2 )" >> $GITHUB_OUTPUT
 
       # We will update this branch by setting the new version and pushing it
       - name: Determine release branch name
@@ -66,7 +71,7 @@ jobs:
           RELEASE_VERSION: ${{ github.event.release.tag_name }}
 
       - name: Compile and Test
-        run: mvn -B package generate-sources source:jar javadoc:jar -DskipTests
+        run: mvn -B package generate-sources source:jar javadoc:jar
 
       - name: Generate sbom reports
         run: |
